# Generated by Django 3.0.3 on 2020-11-23 14:32

from django.db import migrations, models
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='bank_account',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='bankAccount', null=True),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='bank_account',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='bankAccount', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='accountancy_account',
            field=models.CharField(blank=True, db_column='AccountancyAccount', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='address',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='code',
            field=models.CharField(db_column='PolicyHolderCode', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='contact_name',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='ContractName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='payment_reference',
            field=models.CharField(blank=True, db_column='PaymentReference', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='accountancy_account',
            field=models.CharField(blank=True, db_column='AccountancyAccount', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='address',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='code',
            field=models.CharField(db_column='PolicyHolderCode', max_length=32),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='contact_name',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='ContractName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='payment_reference',
            field=models.CharField(blank=True, db_column='PaymentReference', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=16, null=True),
        ),
    ]
