# Generated by Django 3.0.3 on 2020-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0002_auto_20201123_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='activity_code',
            field=models.IntegerField(blank=True, db_column='ActivityCode', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='legal_form',
            field=models.IntegerField(blank=True, db_column='LegalForm', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='activity_code',
            field=models.IntegerField(blank=True, db_column='ActivityCode', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='legal_form',
            field=models.IntegerField(blank=True, db_column='LegalForm', null=True),
        ),
    ]
