# Generated by Django 3.0.3 on 2020-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0003_auto_20201124_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='bank_account',
            field=models.TextField(blank=True, db_column='bankAccount', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='contact_name',
            field=models.TextField(blank=True, db_column='ContactName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='bank_account',
            field=models.TextField(blank=True, db_column='bankAccount', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='contact_name',
            field=models.TextField(blank=True, db_column='ContactName', max_length=255, null=True),
        ),
    ]
