# Generated by Django 3.0.3 on 2020-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0004_auto_20201125_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='contact_name',
            field=models.TextField(blank=True, db_column='ContactName', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='contact_name',
            field=models.TextField(blank=True, db_column='ContactName', null=True),
        ),
    ]
