# Generated by Django 3.0.3 on 2020-11-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0010_auto_20201126_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True),
        ),
    ]
