# Generated by Django 3.0.3 on 2020-11-26 12:56

from django.db import migrations
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0011_auto_20201126_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='address',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='bank_account',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='bankAccount', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholder',
            name='contact_name',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='ContactName', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='address',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='Address', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='bank_account',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='bankAccount', null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='contact_name',
            field=jsonfallback.fields.FallbackJSONField(blank=True, db_column='ContactName', null=True),
        ),
    ]
