# Generated by Django 3.0.3 on 2020-12-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_healthfacilitycatchment_healthfacilitylegalform_healthfacilitymutation_healthfacilitysublevel'),
        ('policyholder', '0012_auto_20201126_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpolicyholder',
            name='locations_uuid',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='locations_uuid',
        ),
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='location_ids',
            field=models.ForeignKey(blank=True, db_column='LocationsID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.Location'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='location_ids',
            field=models.ForeignKey(blank=True, db_column='LocationsID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.Location'),
        ),
    ]
