# Generated by Django 3.0.3 on 2020-12-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0014_auto_20201201_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpolicyholder',
            old_name='locations_uuid',
            new_name='location_ids',
        ),
        migrations.RenameField(
            model_name='policyholder',
            old_name='locations_uuid',
            new_name='location_ids',
        ),
    ]
