# Generated by Django 3.0.3 on 2020-12-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_healthfacilitycatchment_healthfacilitylegalform_healthfacilitymutation_healthfacilitysublevel'),
        ('contribution_plan', '0002_auto_20201120_1143'),
        ('policyholder', '0015_auto_20201201_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpolicyholder',
            name='location_ids',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='location_ids',
        ),
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='locations',
            field=models.ForeignKey(blank=True, db_column='LocationsId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.Location'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='locations',
            field=models.ForeignKey(blank=True, db_column='LocationsId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.Location'),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholdercontributionplan',
            name='contribution_plan_bundle',
            field=models.ForeignKey(blank=True, db_column='ContributionPlanBundleId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contribution_plan.ContributionPlanBundle'),
        ),
        migrations.AlterField(
            model_name='historicalpolicyholderinsuree',
            name='contribution_plan_bundle',
            field=models.ForeignKey(blank=True, db_column='ContributionPlanBundleId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contribution_plan.ContributionPlanBundle'),
        ),
        migrations.AlterField(
            model_name='policyholdercontributionplan',
            name='contribution_plan_bundle',
            field=models.ForeignKey(db_column='ContributionPlanBundleId', on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.ContributionPlanBundle'),
        ),
        migrations.AlterField(
            model_name='policyholderinsuree',
            name='contribution_plan_bundle',
            field=models.ForeignKey(db_column='ContributionPlanBundleId', on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.ContributionPlanBundle'),
        ),
    ]
